# Generated by Django 2.2.12 on 2022-08-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_auto_20220805_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.CharField(max_length=300, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='serviceApp', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Actualizado'),
        ),
    ]
