# Generated by Django 2.2.12 on 2022-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0003_auto_20220805_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('position', models.CharField(max_length=30, verbose_name='Puesto')),
                ('image', models.ImageField(upload_to='serviceApp', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personal',
            },
        ),
    ]
