# Generated by Django 2.2 on 2022-08-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='product_id',
            new_name='product',
        ),
    ]
